### ISSUE TITLE
Search contracts window is not displaying active contracts in CFD database

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#485]
Dear Team,

When we search contracts it displays abandoned, closed contracts but not Active contracts in CFD database. Kindly check and do needful.

Thanks,

![no active contracts](https://cloud.githubusercontent.com/assets/4435890/3505358/b60d7a88-065c-11e4-9a36-263dd3c61c65.png)

**Comment by PavelBastov** [comment]
I think it displays all of them, you just have to keep moving to the next page.
