### ISSUE TITLE
Dashboard PAR is not equal to PAR reports

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#538]
Dear Team,

For CFD, the PAR in Dashboard is not equal to the reports. Saridha from CFD says the reports are fine but the dashboard shows wrong. I have researched on the issue where I found dashboard PAR is not equal to the reports. Kindly look into the issue and do needful. In-case if you need database backup I will drop you through Skype or email.
Version = 14.5v

Thanks,
Regards,
ODED Team.

**Comment by etiennemottet** [comment]
Let's check it out in 15.4

**Comment by etiennemottet** [comment]
Guys please let us know if this is still relevent..

**Comment by PavelBastov** [comment]
We still cannot reproduce the issue.
