### ISSUE TITLE
Error messages when attempting to load LocalDB

### ISSUE THREAD

**Issue by aaron4356** [PavelBastov/opencbs#609]
System won't load LocalDB

![bug screenshot1](https://cloud.githubusercontent.com/assets/8870547/5163180/c3aa566c-73f2-11e4-86ee-c3d0f75700cc.jpg)
![bug screenshot2](https://cloud.githubusercontent.com/assets/8870547/5163187/db5d156a-73f2-11e4-8780-72b8c6b6e5cb.jpg)

**Comment by etiennemottet** [comment]
Could not reproduce... Let's close for now....
