### ISSUE TITLE
No translatio to french of the ''collaterals'' menu item and in the help section

### ISSUE THREAD

**Issue by etiennemottet** [PavelBastov/opencbs#675]
It should say ''Gages''
I suppose there is no translation for other languages either.
We should add them...

In the help section:
Contact us -> Contactez nous
Get help from forum -> Accédez à notre Forum
Visit OPENCBS.com -> Visitez OPENCBS.com

In russian:  Genya

In spanish : Aaron

**Comment by aaron4356** [comment]
Contactar con nosotros, Accuedo a nuestro Foro, Visita OPENCBS.com, Colateral

**Comment by evgeniyabdukarimov** [comment]
Contact us -> Свяжитесь с нами
Get help from forum -> Помощь на форуме
Visit OPENCBS.com -> Посетите OPENCBS.com
