### ISSUE TITLE
Choose Schedule Type and Installment Type at the loan level

### ISSUE THREAD

**Issue by PavelBastov** [PavelBastov/opencbs#710]
To add extra flexibility at the loan level, we want to introduce a couple of controls into the Loan Details tab of the Client Form: a drop-down for Schedule Type and Installment Type.

As well, in the loan product window we want to add the option "All" to both those drop-downs. 

The new behavior should be this (let's take Schedule Type as an example): if we choose "All" in Schedule Type drop-down, the user should be able to choose any type in the Loan Details window. On the other hand, if we choose a concrete type, like Flat, in the loan product window. The type should be defaulted to that value in the loan window, and the drop-down disabled.

**Comment by evgeniyabdukarimov** [comment]
Done
