### ISSUE TITLE
Make sure title case is followed on Fast Repayment window

### ISSUE THREAD

**Issue by aaron4356** [PavelBastov/opencbs#722]
column headings and "Payment Method" label (should be "Payment method")

**Comment by PavelBastov** [comment]
What about "Loan officer", "Total principal", "Total interest", "Total penalty", "Grand total", and all the compound column headers?

**Comment by PavelBastov** [comment]
What about the column headers and other labels like "Total interest"?

**Comment by aaron4356** [comment]
Column headings should all be title case...if you see caps issues anywhere
you can change it. Askar knows the rules well
