### ISSUE TITLE
Create document tracking module

### ISSUE THREAD

**Issue by aaron4356** [PavelBastov/opencbs#775]

**Comment by etiennemottet** [comment]
The subfolders retract at any update. It is not very convenient. Can we change that.

**Comment by etiennemottet** [comment]
Subfolders are still retracing. This is not really convenient...

**Comment by EmilyWatsonCF** [comment]
yeah, I've been working on making the folder name by the name of a client.
and implementing a logic for it not to make another folder if the client is renamed, 
but reroute to the old folder. Still in process.

**Comment by etiennemottet** [comment]
In addition, if you are working with different instances of OPENCBS, all the folders get created in the same section, which is not very convenient. We could find a way to partition them by database...

**Comment by etiennemottet** [comment]
Ok for a first draft. Later on we need to fix the refreshing issue as for now we need to close and reopen the client to see the folder appear...
