### ISSUE TITLE
VTN requires Validation at Custom fields.

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#779]
Dear Team,

VTN requires validation check at custom fields. For Ex- If the user enters 9 digits instead of 10 digits in mobile number field it should show the pop-up.

**Comment by etiennemottet** [comment]
Probably not an issue. We are gonna check how to do that.

**Comment by etiennemottet** [comment]
Ready to be used. We need the needs of VTN and configure the masks.
