### ISSUE TITLE
Report requirement

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#786]
CFD require the OLB per groupwise  report for with they wanted to choose the group name at meta file generation. ODED created the report, when we select the branch in the meta file it should show the related groups but it shows all. Kindly guide us.

**Comment by etiennemottet** [comment]
Is this still relevent guys?

**Comment by PavelBastov** [comment]
Can we somehow apply the trick we did for VTN: instead of showing two dropdown boxes display one tree of branches with village banks beneath?

**Comment by odedtech** [comment]
Here their main intention for the report is they wanted to check the OLB of a particular group with its group members. So they requested us to have the following at meta level to generate the report.
- Date choosing
- Subordinate
- Branch
- Group Name selection.
Here we have done this successfully. The only thing not achieved is when we select a branch before a group selection then it should show the groups of the selected branch but it shows all.
