### ISSUE TITLE
Reports Slow - VTN

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#788]
Dear team,

The following reports are slow for VTN. Takes more than 1 minute. Kindly do needful.
1.. Delinquency Report..
2.. Portfolio Master data
3.. Information on Interest
4.. Accrued Interest

**Comment by etiennemottet** [comment]
On our side delinquency report takes 5 seconds to open... This may due to the fact DB and system are on 2 different servers. Can you guys check that out....

**Comment by etiennemottet** [comment]
Ok I checked the specific reports for VTN. They are indeed slow. We'll check that out...

**Comment by etiennemottet** [comment]
Splitted into #810 and #812   . Any other report to improve?
