### ISSUE TITLE
Repayment Issue

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#789]
Dear Team,

For one of our client IRCED, the system is showing error while making repayment. When I see through schedule in loan repayment window the installments are in red as they delayed but when i go through event is displays the payment is done. Kindly do need full. Feel free to ask for database if required.

Thanks,
Regards,
Anantwar Gangadhar.

![recovery issue](https://cloud.githubusercontent.com/assets/4435890/7509776/bb03dc40-f4b2-11e4-96c0-2fd7330d35b4.png)
![schedule late payments](https://cloud.githubusercontent.com/assets/4435890/7509777/bb06f10a-f4b2-11e4-9640-e09dc0a9b3bf.png)
![payment events](https://cloud.githubusercontent.com/assets/4435890/7509778/bb087886-f4b2-11e4-9321-9464e3bcbdc1.png)

**Comment by etiennemottet** [comment]
If still relevent please post on support skype and we will queue
