### ISSUE TITLE
Let's add corporate client information below print button

### ISSUE THREAD

**Issue by Ismailova** [PavelBastov/opencbs#805]
![print botton](https://cloud.githubusercontent.com/assets/11435617/7604040/c4f7b1bc-f95e-11e4-8070-b483e429d647.png)

**Comment by etiennemottet** [comment]
This internal form is to be done with Crystal report first and must include:
- Corporate details
- Address
- Contacts
- Loan contracts
- Saving contracts
The internal form ''client personal information'' can be used as example.

**Comment by etiennemottet** [comment]
Guys it doesn't appear in the build for me.Can you make sure it has been included in the msi.
