### ISSUE TITLE
Issues running openCBS on local machine

### ISSUE THREAD

**Issue by timkaboya** [PavelBastov/opencbs#862]
Using VS2013, I forked the openCBS project.
After updating to restore missing packages, I still have 1 error on "if not exist" and "xcopy.  There are also 26 warnings due to conflicting assemblies and other stuff. 

How do I fix this and get the sample working.

**Comment by jayrulez** [comment]
It's a post-build process. I think I solved that by creating the directory C:\OpenCBSLibs and C:\OpenCBSLibs\Update
