### ISSUE TITLE
error massage when attempted mssql remote connection

### ISSUE THREAD

**Issue by llsatellite** [PavelBastov/opencbs#889]
im getting this error after got connected to the remote server i click to create new data base can some one help me to get this running remotely mssql

![image](https://cloud.githubusercontent.com/assets/12961401/8246862/33f862a0-160b-11e5-8f0b-afa3d4c90d1e.png)

**Comment by etiennemottet** [comment]
We will be glad to assist you. Join us on skype at info.opencbs and we will investigate the issue.
