### ISSUE TITLE
Client registration tracking

### ISSUE THREAD

**Issue by evgeniyabdukarimov** [PavelBastov/opencbs#890]
When user registers the new client in DB, we have to store additional info in that:
 - Date of registration
 - User, who registered the client

Additionally, do the same when user registers the loan, means date of loan registration and user who did it.

**Comment by PavelBastov** [comment]
I get this error when creating a new individual client on a brand new database:

![image](https://cloud.githubusercontent.com/assets/4413973/8447410/20f27866-1fda-11e5-96f9-b98b011516f6.png)

You forgot to update the database creation script.

**Comment by PavelBastov** [comment]
Also, remove the `created_at` column, it seems to duplicate `creation_date`.

**Comment by PavelBastov** [comment]
By default, set `created_by` to 1.
