### ISSUE TITLE
Loan products: Schedule definition error

### ISSUE THREAD

**Issue by evgeniyabdukarimov** [PavelBastov/opencbs#893]
Loan products: Schedule definition error

Upgraded to latest build (opencbs-15.7.1293.3cd6d8a-x64).
Database of SHR
Loan products shows nothing for schedule type, but should be defined.
See screenshot
![1](https://cloud.githubusercontent.com/assets/4415719/8515729/5e0209bc-23ca-11e5-9723-18b5616b7df5.png)

**Comment by artemstarchkov** [comment]
After a base backup in the table Packages in the column script_name it was restored old value a script name, with his such name doesn't exist. Therefore in the column type schedule it wasn't displayed.

**Comment by evgeniyabdukarimov** [comment]
Done
