### ISSUE TITLE
In general settings week-end days accept any number.

### ISSUE THREAD

**Issue by etiennemottet** [PavelBastov/opencbs#912]

**Comment by PavelBastov** [comment]
If enter and invalid value, I see the error message, but then the field is cleared and the empty value is saved. I think a better solution would be to replace the edit box with an up-down spinner.

**Comment by PavelBastov** [comment]
And now I cannot log into the system. From minor the bug turned into severe!

**Comment by PavelBastov** [comment]
Actually, I could fix it be resetting the default value to "0".
