### ISSUE TITLE
Date format in General Settings

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#922]
Hello team,
It could be better if this option is available in drop down list. The reason, if we edit manually the format applies at Settings level but the format is not proper in the application at any part of date.

**Comment by PavelBastov** [comment]
Moved to GitLab.

**Comment by jayrulez** [comment]
Is the gitlab repo public?

**Comment by PavelBastov** [comment]
It's public, and it will stay public, but we are moving to our own code hosting platform. Thus, going forward all the commits will be performed there.

You can find the repo here:
http://code.opencbs.com/opencbs/OPENCBS
