### ISSUE TITLE
Enforce ID pattern in General Settings

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#926]
This was used earlier to fix the ID pattern with respect to automatic ID is = NO. Now this is not available. Due to this at user level the system accepts any ID even we configure the standard ID pattern. Kindly put back this again in the interface.

**Comment by etiennemottet** [comment]
For saving the client the first time it works. It seems fixed for us.
If not, please move it to gitlab and be more precise in explanations.
