### ISSUE TITLE
Product configuration not applying for NSG/VB

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#932]
Hello, 
When I configure Integer type= ALL, Interest rate type = ALL at product level, it is not working at NSG disbursement. (BUG)

**Comment by etiennemottet** [comment]
This has never been available in NSG. this is not a bug. This is a new feature. It will be included in new VB disbursment capacity.

**Comment by PavelBastov** [comment]
Moved to GitLab.
