### ISSUE TITLE
Three stage loan approval for SMCL

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#938]
Here our client SMCL requires three stage loan approval while disbursement. Which mean there should be three users from higher level will approve the loan. The loan should not be disbursed until the users approve. Here for example the user with FA role enters the loan, KYC details till the pending stage. BM recommends/validates the loans which was entered by FA(this is first stage approval), ZM approves the loan after BM validates (this is second stage approval), finally HO users approves once ZM approves (this is third stage approval).
and secondly Every status should have the right to control at user Roles level. It means each user FA or BM or ZM or HO or others... every one can modify the status but each status( Approve, validate, pending, refuse ....) should be linked with the security check at roles for the user.

**Comment by PavelBastov** [comment]
Moved to GitLab.
