### ISSUE TITLE
Customized Dashboard for GMF

### ISSUE THREAD

**Issue by odedtech** [PavelBastov/opencbs#939]
Hello team,
Our client GMF requires the customized dashboard. Here they have two categories of loans. 1) OWN LOANS, 2) MANAGED LOANS. 
Own Loans: Loan product of GMF.
Managed : Loan product of Banks (managing by GMF)
Each categories has their own loan products. Ex: Loan 1, 2, 3  belongs to Own loans, Loan A, B, C belongs to Managed. Now in dash board in the product section they need two filters OWN and MANAGED instead of showing all loan products. When we choose OWN or MANAGED filters its should show the PAR and portfolio information of its respective products.

**Comment by PavelBastov** [comment]
Moved to GitLab.
