### ISSUE TITLE
A first chance exception : looping login

### ISSUE THREAD

**Issue by lmojela** [PavelBastov/opencbs#948]
When I run the source code, login keeps looping.
On looking at the output I see this error: 
A first chance exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.dll

**Comment by aaskat** [comment]
Hello.
You can get last source code from
http://bitbucket.opencbs.com/projects/OPENCBS/repos/opencbs/browse

**Comment by lmojela** [comment]
Hi @aaskat 
Thank you, let me try the newer source code.

**Comment by lmojela** [comment]
solved
